---
app_servers: "{{ ( groups['app_servers'] | default([]) ) + ( groups['meta-app_servers_AnsibleGroup'] | default([]) ) }}"
load_balancers: "{{ ( groups['load_balancers'] | default([]) ) + ( groups['meta-load_balancers_AnsibleGroup'] | default([]) ) }}"