---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask

  vars:
    flask_app_name: resource_hub
    flask_repo: https://github.com/tonykay/resource_hub.git
    flask_scm_ref: main
    flask_app_lauch_script: /usr/local/bin/launch_resource_hub

  roles:
    - dns
    - register_satellite