---
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true

  tags:
    - load_balancers
  
  vars:
    firewall_tcp_port:
      - 80

  roles:
    - dns
    - register_satellite
    - firewall
    - haproxy