---
- name: Provision Final Lab Servers
  hosts: localhost
  vars:
    guid: "6343"
  roles:
    - provision_servers
  pre_tasks:
    - name: "Set Server Information"
      loop: "{{ groups['internal'] }}"
      delegate_to: "{{ item }}"
      delegate_facts: true
      set_fact:
        provision_information:
          image: rhel-8.3
          flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
          security_group: "{{ guid }}-HostSG"
          network: "{{ guid }}-dev-network"
          keypair: "{{ guid }}-keypair"
          metadata: "{{ hostvars[item]['group_names'] | product(['AnsibleGroup']) | map('join', '=') | join(',') }},deployment_name=final_lab"
            