---
- name: End to end smoke tests
# Use host groups from hosts and metadata so override can be used in the dynamic inventory. Makes for a cleaner inventory
  hosts: 
    - app_servers
    - meta-app_servers_AnsibleGroup
    - database_servers
    - meta-database_servers_AnsibleGroup
  gather_facts: true
  become: true
  tags:
    - smoketest
  vars:
    app_servers: "{{ ( groups['app_servers'] | default([]) ) + ( groups['meta-app_servers_AnsibleGroup'] | default([]) ) }}"
    database_servers: "{{ ( groups['database_servers'] | default([]) ) + ( groups['meta-database_servers_AnsibleGroup'] | default([]) ) }}"

  tasks:

    - name: Smoketest Postgres database
      postgresql_ping:
        db: flask_db
        login_host: "{{ database_servers[0] }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: End to end smoke tests
  hosts:
    - app_servers
    - meta-app_servers_AnsibleGroup
  become: false
  gather_facts: false
  tags:
    - smoketest  
  tasks:
 
    - name: Check webserver for correct response
      uri:
        url: "http://frontend1/ping"
        return_content: yes
      until: '"alive" in result.content'
      retries: 10
      delay: 1
      register: result
      delegate_to: localhost