---
- name: Create instances
  openstack.cloud.server: 
    state: present
    cloud: "devstack"
    name: "{{ item }}"
    image: "{{ hostvars[item]['provision_information']['image'] }}"
    key_name: "{{ hostvars[item]['provision_information']['keypair'] }}"
    flavor: "{{ hostvars[item]['provision_information']['flavor'] }}"
    security_groups: "{{ hostvars[item]['provision_information']['security_group'] }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ hostvars[item]['provision_information']['network'] }}"
    meta: "{{ hostvars[item]['provision_information']['metadata'] }}" 
    userdata: |
      #!/bin/bash
  loop: "{{ groups['internal'] }}"
