---
- name: Dump vars
  debug:
    msg: "{{ hostvars[item] }}"

- name: Create instances
  openstack.cloud.server: 
    state: absent
    cloud: "{{ guid }}-project"
    name: "{{ item }}"
    image: "{{ hostvars[item]['image'] }}"
    key_name: "{{ hostvars[item]['keypair'] }}"
    flavor: "{{ hostvars[item]['flavor'] }}"
    security_groups: "{{ hostvars[item]['security_group'] }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: "{{ hostvars[item]['network'] }}"
    meta: "{{ hostvars[item]['metadata'] }}" 
    userdata: |
      #!/bin/bash
  loop: "{{ groups['internal'] }}"
