guid: ""
servers: []
#  - name: server1
#    image: rhel-8.3
#    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
#    security_group: "{{ guid }}-HostSG"
#    network: "{{ guid }}-dev-network"
#    keypair: "{{ guid }}-keypair"
#    metadata: "AnsibleGroup=osp_instances,deployment_name=dev"